"""replace_is_deleted_with_deleted_at

Revision ID: 0a3f724d30b8
Revises: 3b7e5a5f4bb4
Create Date: 2026-04-27 23:39:09.110367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3f724d30b8'
down_revision: Union[str, Sequence[str], None] = '3b7e5a5f4bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_packs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_card_packs_author_list'), table_name='card_packs')
    op.create_index('ix_card_packs_author_list', 'card_packs', ['author_id', 'deleted_at', 'created_at'], unique=False)
    op.drop_index(op.f('ix_card_packs_public_most_saved'), table_name='card_packs')
    op.create_index('ix_card_packs_public_most_saved', 'card_packs', ['is_public', 'deleted_at', 'status', 'saves_count'], unique=False)
    op.drop_index(op.f('ix_card_packs_public_new'), table_name='card_packs')
    op.create_index('ix_card_packs_public_new', 'card_packs', ['is_public', 'deleted_at', 'status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_card_packs_public_top_rated'), table_name='card_packs')
    op.create_index('ix_card_packs_public_top_rated', 'card_packs', ['is_public', 'deleted_at', 'status', 'rating_average'], unique=False)
    op.create_index(op.f('ix_card_packs_deleted_at'), 'card_packs', ['deleted_at'], unique=False)
    op.drop_column('card_packs', 'is_deleted')
    op.add_column('maps', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_maps_is_deleted'), table_name='maps')
    op.drop_index(op.f('ix_maps_author_list'), table_name='maps')
    op.create_index('ix_maps_author_list', 'maps', ['author_id', 'deleted_at', 'created_at'], unique=False)
    op.drop_index(op.f('ix_maps_public_most_saved'), table_name='maps')
    op.create_index('ix_maps_public_most_saved', 'maps', ['is_public', 'deleted_at', 'status', 'saves_count'], unique=False)
    op.drop_index(op.f('ix_maps_public_new'), table_name='maps')
    op.create_index('ix_maps_public_new', 'maps', ['is_public', 'deleted_at', 'status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_maps_public_top_rated'), table_name='maps')
    op.create_index('ix_maps_public_top_rated', 'maps', ['is_public', 'deleted_at', 'status', 'rating_average'], unique=False)
    op.create_index(op.f('ix_maps_deleted_at'), 'maps', ['deleted_at'], unique=False)
    op.drop_column('maps', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_maps_deleted_at'), table_name='maps')
    op.drop_index('ix_maps_public_top_rated', table_name='maps')
    op.create_index(op.f('ix_maps_public_top_rated'), 'maps', ['is_public', 'is_deleted', 'status', 'rating_average'], unique=False)
    op.drop_index('ix_maps_public_new', table_name='maps')
    op.create_index(op.f('ix_maps_public_new'), 'maps', ['is_public', 'is_deleted', 'status', 'created_at'], unique=False)
    op.drop_index('ix_maps_public_most_saved', table_name='maps')
    op.create_index(op.f('ix_maps_public_most_saved'), 'maps', ['is_public', 'is_deleted', 'status', 'saves_count'], unique=False)
    op.drop_index('ix_maps_author_list', table_name='maps')
    op.create_index(op.f('ix_maps_author_list'), 'maps', ['author_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index(op.f('ix_maps_is_deleted'), 'maps', ['is_deleted'], unique=False)
    op.drop_column('maps', 'deleted_at')
    op.add_column('card_packs', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_card_packs_deleted_at'), table_name='card_packs')
    op.drop_index('ix_card_packs_public_top_rated', table_name='card_packs')
    op.create_index(op.f('ix_card_packs_public_top_rated'), 'card_packs', ['is_public', 'is_deleted', 'status', 'rating_average'], unique=False)
    op.drop_index('ix_card_packs_public_new', table_name='card_packs')
    op.create_index(op.f('ix_card_packs_public_new'), 'card_packs', ['is_public', 'is_deleted', 'status', 'created_at'], unique=False)
    op.drop_index('ix_card_packs_public_most_saved', table_name='card_packs')
    op.create_index(op.f('ix_card_packs_public_most_saved'), 'card_packs', ['is_public', 'is_deleted', 'status', 'saves_count'], unique=False)
    op.drop_index('ix_card_packs_author_list', table_name='card_packs')
    op.create_index(op.f('ix_card_packs_author_list'), 'card_packs', ['author_id', 'is_deleted', 'created_at'], unique=False)
    op.drop_column('card_packs', 'deleted_at')
    # ### end Alembic commands ###
