"""add_background_url_to_map_themes

Revision ID: 0e819e122fa0
Revises: 56ce1f132070
Create Date: 2026-06-05 16:46:02.379383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e819e122fa0'
down_revision: Union[str, Sequence[str], None] = '56ce1f132070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_themes', sa.Column('background_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_themes', 'background_url')
    # ### end Alembic commands ###
