"""add schema to card_type

Revision ID: 3b7e5a5f4bb4
Revises: d0032af7248e
Create Date: 2026-04-26 17:53:18.403306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7e5a5f4bb4'
down_revision: Union[str, Sequence[str], None] = 'd0032af7248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_types', sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_types', 'schema')
    # ### end Alembic commands ###
