"""add_games_won_to_user

Revision ID: 56ce1f132070
Revises: 7d316ca0dd73
Create Date: 2026-05-28 18:06:58.117910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ce1f132070'
down_revision: Union[str, Sequence[str], None] = '7d316ca0dd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('games_won', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'games_won')
    # ### end Alembic commands ###
