"""Add deleted_at and partial indexes

Revision ID: 66a1f584994f
Revises: 0a3f724d30b8
Create Date: 2026-04-28 19:20:38.983868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a1f584994f'
down_revision: Union[str, Sequence[str], None] = '0a3f724d30b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_packs_author_list'), table_name='card_packs')
    op.drop_index(op.f('ix_card_packs_public_most_saved'), table_name='card_packs')
    op.create_index('ix_card_packs_public_most_saved', 'card_packs', ['saves_count'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index(op.f('ix_card_packs_public_new'), table_name='card_packs')
    op.create_index('ix_card_packs_public_new', 'card_packs', ['created_at'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index(op.f('ix_card_packs_public_top_rated'), table_name='card_packs')
    op.create_index('ix_card_packs_public_top_rated', 'card_packs', ['rating_average'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index('ix_card_packs_author_active', 'card_packs', ['author_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_card_packs_author_trash', 'card_packs', ['author_id', 'deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('ix_card_packs_public_type', 'card_packs', ['type_id'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index(op.f('ix_maps_author_list'), table_name='maps')
    op.drop_index(op.f('ix_maps_public_most_saved'), table_name='maps')
    op.create_index('ix_maps_public_most_saved', 'maps', ['saves_count'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index(op.f('ix_maps_public_new'), table_name='maps')
    op.create_index('ix_maps_public_new', 'maps', ['created_at'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index(op.f('ix_maps_public_top_rated'), table_name='maps')
    op.create_index('ix_maps_public_top_rated', 'maps', ['rating_average'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index('ix_maps_author_active', 'maps', ['author_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_maps_author_trash', 'maps', ['author_id', 'deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('ix_maps_public_template', 'maps', ['template_id'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maps_public_template', table_name='maps', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index('ix_maps_author_trash', table_name='maps', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('ix_maps_author_active', table_name='maps', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_maps_public_top_rated', table_name='maps', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_maps_public_top_rated'), 'maps', ['is_public', 'deleted_at', 'status', 'rating_average'], unique=False)
    op.drop_index('ix_maps_public_new', table_name='maps', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_maps_public_new'), 'maps', ['is_public', 'deleted_at', 'status', 'created_at'], unique=False)
    op.drop_index('ix_maps_public_most_saved', table_name='maps', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_maps_public_most_saved'), 'maps', ['is_public', 'deleted_at', 'status', 'saves_count'], unique=False)
    op.create_index(op.f('ix_maps_author_list'), 'maps', ['author_id', 'deleted_at', 'created_at'], unique=False)
    op.drop_index('ix_card_packs_public_type', table_name='card_packs', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.drop_index('ix_card_packs_author_trash', table_name='card_packs', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('ix_card_packs_author_active', table_name='card_packs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_card_packs_public_top_rated', table_name='card_packs', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_card_packs_public_top_rated'), 'card_packs', ['is_public', 'deleted_at', 'status', 'rating_average'], unique=False)
    op.drop_index('ix_card_packs_public_new', table_name='card_packs', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_card_packs_public_new'), 'card_packs', ['is_public', 'deleted_at', 'status', 'created_at'], unique=False)
    op.drop_index('ix_card_packs_public_most_saved', table_name='card_packs', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_card_packs_public_most_saved'), 'card_packs', ['is_public', 'deleted_at', 'status', 'saves_count'], unique=False)
    op.create_index(op.f('ix_card_packs_author_list'), 'card_packs', ['author_id', 'deleted_at', 'created_at'], unique=False)
    # ### end Alembic commands ###
