"""remove_map_templates_add_size_to_maps_add_themes

Revision ID: 7d316ca0dd73
Revises: f4d77631c92a
Create Date: 2026-05-26 19:29:10.391426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d316ca0dd73'
down_revision: Union[str, Sequence[str], None] = 'f4d77631c92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create map_themes table
    op.create_table('map_themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('scene_url_small', sa.String(), nullable=True),
    sa.Column('scene_url_medium', sa.String(), nullable=True),
    sa.Column('scene_url_large', sa.String(), nullable=True),
    sa.Column('piece_model_url', sa.String(), nullable=True),
    sa.Column('color_textures', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_themes_code'), 'map_themes', ['code'], unique=True)

    # 2. Add new columns as nullable first (for existing rows)
    op.add_column('maps', sa.Column('size', sa.String(), nullable=True))
    op.add_column('maps', sa.Column('max_fields_count', sa.Integer(), nullable=True))

    # 3. Backfill existing rows from map_templates
    op.execute("""
        UPDATE maps
        SET size = 'MEDIUM',
            max_fields_count = COALESCE(
                (SELECT mt.max_fields_count FROM map_templates mt WHERE mt.id = maps.template_id),
                48
            )
        WHERE size IS NULL
    """)

    # 4. Make columns NOT NULL after backfill
    op.alter_column('maps', 'size', nullable=False)
    op.alter_column('maps', 'max_fields_count', nullable=False)

    # 5. Drop FK, indexes, and column referencing map_templates (BEFORE dropping the table)
    op.drop_index(op.f('ix_maps_public_template'), table_name='maps', postgresql_where="((is_public IS TRUE) AND (deleted_at IS NULL) AND ((status)::text = 'ACTIVE'::text))")
    op.drop_index(op.f('ix_maps_template_id'), table_name='maps')
    op.drop_constraint(op.f('maps_template_id_fkey'), 'maps', type_='foreignkey')
    op.drop_column('maps', 'template_id')

    # 6. Now safe to drop map_templates
    op.drop_index(op.f('ix_map_templates_code'), table_name='map_templates')
    op.drop_table('map_templates')

    # 7. Create new indexes
    op.create_index('ix_maps_public_size', 'maps', ['size'], unique=False, postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_maps_size'), 'maps', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('maps_template_id_fkey'), 'maps', 'map_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_maps_size'), table_name='maps')
    op.drop_index('ix_maps_public_size', table_name='maps', postgresql_where=sa.text("is_public IS true AND deleted_at IS NULL AND status = 'ACTIVE'"))
    op.create_index(op.f('ix_maps_template_id'), 'maps', ['template_id'], unique=False)
    op.create_index(op.f('ix_maps_public_template'), 'maps', ['template_id'], unique=False, postgresql_where="((is_public IS TRUE) AND (deleted_at IS NULL) AND ((status)::text = 'ACTIVE'::text))")
    op.drop_column('maps', 'max_fields_count')
    op.drop_column('maps', 'size')
    op.create_table('map_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_fields_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('3d_model_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('map_templates_pkey'))
    )
    op.create_index(op.f('ix_map_templates_code'), 'map_templates', ['code'], unique=True)
    op.drop_index(op.f('ix_map_themes_code'), table_name='map_themes')
    op.drop_table('map_themes')
    # ### end Alembic commands ###
