"""Init database

Revision ID: 8279e133c892
Revises: 
Create Date: 2026-04-19 19:28:53.028540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8279e133c892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('core_mechanic', sa.String(), nullable=False),
    sa.Column('allowed_modifiers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_card_types_core_mechanic'), 'card_types', ['core_mechanic'], unique=False)
    op.create_table('map_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_fields_count', sa.Integer(), nullable=False),
    sa.Column('3d_model_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_templates_code'), 'map_templates', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_registration_finished', sa.Boolean(), nullable=False),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('card_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['card_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_packs_author_id'), 'card_packs', ['author_id'], unique=False)
    op.create_index('ix_card_packs_author_list', 'card_packs', ['author_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_card_packs_public_most_saved', 'card_packs', ['is_public', 'is_deleted', 'status', 'saves_count'], unique=False)
    op.create_index('ix_card_packs_public_new', 'card_packs', ['is_public', 'is_deleted', 'status', 'created_at'], unique=False)
    op.create_index('ix_card_packs_public_top_rated', 'card_packs', ['is_public', 'is_deleted', 'status', 'rating_average'], unique=False)
    op.create_index(op.f('ix_card_packs_status'), 'card_packs', ['status'], unique=False)
    op.create_index(op.f('ix_card_packs_type_id'), 'card_packs', ['type_id'], unique=False)
    op.create_table('maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_author_id'), 'maps', ['author_id'], unique=False)
    op.create_index('ix_maps_author_list', 'maps', ['author_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index(op.f('ix_maps_is_deleted'), 'maps', ['is_deleted'], unique=False)
    op.create_index('ix_maps_public_most_saved', 'maps', ['is_public', 'is_deleted', 'status', 'saves_count'], unique=False)
    op.create_index('ix_maps_public_new', 'maps', ['is_public', 'is_deleted', 'status', 'created_at'], unique=False)
    op.create_index('ix_maps_public_top_rated', 'maps', ['is_public', 'is_deleted', 'status', 'rating_average'], unique=False)
    op.create_index(op.f('ix_maps_status'), 'maps', ['status'], unique=False)
    op.create_index(op.f('ix_maps_template_id'), 'maps', ['template_id'], unique=False)
    op.create_table('card_pack_ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_pack_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_card_pack_ratings_score'),
    sa.ForeignKeyConstraint(['card_pack_id'], ['card_packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_pack_id')
    )
    op.create_index(op.f('ix_card_pack_ratings_card_pack_id'), 'card_pack_ratings', ['card_pack_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('card_pack_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_pack_id'], ['card_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_pack_id'), 'cards', ['card_pack_id'], unique=False)
    op.create_table('map_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('card_pack_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['card_pack_id'], ['card_packs.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_fields_card_pack_id'), 'map_fields', ['card_pack_id'], unique=False)
    op.create_index(op.f('ix_map_fields_map_id'), 'map_fields', ['map_id'], unique=False)
    op.create_table('map_ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_map_ratings_score'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'map_id')
    )
    op.create_index(op.f('ix_map_ratings_map_id'), 'map_ratings', ['map_id'], unique=False)
    op.create_table('saved_card_packs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_pack_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_pack_id'], ['card_packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_pack_id')
    )
    op.create_index(op.f('ix_saved_card_packs_card_pack_id'), 'saved_card_packs', ['card_pack_id'], unique=False)
    op.create_table('saved_maps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'map_id')
    )
    op.create_index(op.f('ix_saved_maps_map_id'), 'saved_maps', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_maps_map_id'), table_name='saved_maps')
    op.drop_table('saved_maps')
    op.drop_index(op.f('ix_saved_card_packs_card_pack_id'), table_name='saved_card_packs')
    op.drop_table('saved_card_packs')
    op.drop_index(op.f('ix_map_ratings_map_id'), table_name='map_ratings')
    op.drop_table('map_ratings')
    op.drop_index(op.f('ix_map_fields_map_id'), table_name='map_fields')
    op.drop_index(op.f('ix_map_fields_card_pack_id'), table_name='map_fields')
    op.drop_table('map_fields')
    op.drop_index(op.f('ix_cards_card_pack_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_card_pack_ratings_card_pack_id'), table_name='card_pack_ratings')
    op.drop_table('card_pack_ratings')
    op.drop_index(op.f('ix_maps_template_id'), table_name='maps')
    op.drop_index(op.f('ix_maps_status'), table_name='maps')
    op.drop_index('ix_maps_public_top_rated', table_name='maps')
    op.drop_index('ix_maps_public_new', table_name='maps')
    op.drop_index('ix_maps_public_most_saved', table_name='maps')
    op.drop_index(op.f('ix_maps_is_deleted'), table_name='maps')
    op.drop_index('ix_maps_author_list', table_name='maps')
    op.drop_index(op.f('ix_maps_author_id'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_card_packs_type_id'), table_name='card_packs')
    op.drop_index(op.f('ix_card_packs_status'), table_name='card_packs')
    op.drop_index('ix_card_packs_public_top_rated', table_name='card_packs')
    op.drop_index('ix_card_packs_public_new', table_name='card_packs')
    op.drop_index('ix_card_packs_public_most_saved', table_name='card_packs')
    op.drop_index('ix_card_packs_author_list', table_name='card_packs')
    op.drop_index(op.f('ix_card_packs_author_id'), table_name='card_packs')
    op.drop_table('card_packs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_map_templates_code'), table_name='map_templates')
    op.drop_table('map_templates')
    op.drop_index(op.f('ix_card_types_core_mechanic'), table_name='card_types')
    op.drop_table('card_types')
    # ### end Alembic commands ###
